name: Docker Build and Push

on:
  workflow_call:
    inputs:
      service:
        description: "'frontend' or 'backend'"
        required: true
        type: string
    secrets:
      personal-access-token:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ inputs.service }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate CalVer
        id: version
        uses: ./.github/actions/calver

      - name: Validate docker file
        run: docker compose config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.personal-access-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Lowercase
        id: set_owner
        run: |
          val=${{ github.repository_owner }}
          echo "val=${val,,}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.SERVICE }}
          file: ./${{ env.SERVICE }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.set_owner.outputs.val }}/defi-fullstack-${{ env.SERVICE }}:latest
            ghcr.io/${{ steps.set_owner.outputs.val }}/defi-fullstack-${{ env.SERVICE }}:${{ steps.version.outputs.calver }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/${{ steps.set_owner.outputs.val }}/defi-fullstack-${{ env.SERVICE }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'